export interface Transaction {
    "Identifiant de document": string;
    "Reference document": string;
    "1 Articles CGI": string;
    "2 Articles CGI": string;
    "3 Articles CGI": string;
    "4 Articles CGI": string;
    "5 Articles CGI": string;
    "No disposition": string;
    "Date mutation": string;
    "Nature mutation": string;
    "Valeur fonciere": string;
    "No voie": string;
    "B/T/Q": string;
    "Type de voie": string;
    "Code voie": string;
    "Voie": string;
    "Code postal": string;
    "Commune": string;
    "Code departement": string;
    "Code commune": string;
    "Prefixe de section": string;
    "Section": string;
    "No plan": string;
    "No Volume": string;
    "1er lot": string;
    "Surface Carrez du 1er lot": string;
    "2eme lot": string;
    "Surface Carrez du 2eme lot": string;
    "3eme lot": string;
    "Surface Carrez du 3eme lot": string;
    "4eme lot": string;
    "Surface Carrez du 4eme lot": string;
    "5eme lot": string;
    "Surface Carrez du 5eme lot": string;
    "Nombre de lots": string;
    "Code type local": string;
    "Type local": string;
    "Identifiant local": string;
    "Surface reelle bati": string;
    "Nombre pieces principales": string;
    "Nature culture": string;
    "Nature culture speciale": string;
    "Surface terrain": string;
}